In [1]:
import numpy as np

In [2]:
myarr= np.array([1,2,3,4])

In [3]:
myarr

array([1, 2, 3, 4])

In [4]:
myarr[1]

2

myarr

In [5]:
myarr

array([1, 2, 3, 4])

In [6]:
myarr.shape

(4,)

In [7]:
myarr.dtype

dtype('int32')

In [8]:
myarr= np.array([[7,8,9]])

In [9]:
myarr

array([[7, 8, 9]])

In [10]:
myarr.shape

(1, 3)

In [11]:
myarr.dtype

dtype('int32')

In [12]:
myarr[0,1]=11

In [13]:
myarr

array([[ 7, 11,  9]])

In [14]:
myarr[0,0]

7

In [15]:
myarr[0,0]=22

In [16]:
myarr

array([[22, 11,  9]])

# Conversion from other Python Structures

In [17]:
listarray= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [18]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
listarray.dtype

dtype('int32')

In [20]:
listarray.shape

(3, 3)

In [21]:
listarray.size

9

In [22]:
zeros= np.zeros((2,5))

In [23]:
zeros.shape

(2, 5)

In [24]:
rng=np.arange(11)

In [25]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
id=np.identity(11)

In [27]:
id

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [28]:
id.shape

(11, 11)

In [29]:
arr=np.arange(99)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [31]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [33]:
arr=arr.reshape(3,33)

In [34]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [35]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [36]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [37]:
arr=arr.ravel()

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [39]:
arr.shape

(99,)

In [40]:
array1=np.array([[9,8,7],[6,5,4],[3,2,1]])

In [41]:
array1

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [42]:
array1[0]

array([9, 8, 7])

In [43]:
array1[0,1]

8

In [44]:
array1[1]

array([6, 5, 4])

In [45]:
array1

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [46]:
array1.sum(axis=0)

array([18, 15, 12])

In [47]:
array1.sum(axis=1)

array([24, 15,  6])

In [48]:
array1.T

array([[9, 6, 3],
       [8, 5, 2],
       [7, 4, 1]])

In [49]:
for item in array1.flat:
    print(item)

9
8
7
6
5
4
3
2
1


In [50]:
array1.ndim

2

In [51]:
array1.size

9

In [52]:
array1.nbytes

36

In [53]:
one=np.array([[1,8,10,11]])

In [54]:
one

array([[ 1,  8, 10, 11]])

In [55]:
one.argmax()

3

In [56]:
one.shape

(1, 4)

In [57]:
two=np.array([1,2,3])

In [58]:
two.shape

(3,)

In [59]:
array1

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [60]:
array2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [61]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [62]:
array1

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [63]:
array1+array2

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [64]:
array1*array2

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [65]:
array1.max()

9

In [66]:
array2.min()

1

In [67]:
np.where(array1>6)

(array([0, 0, 0], dtype=int64), array([0, 1, 2], dtype=int64))